// <auto-generated />
using DAL.Application.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DAL.Application.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171104131254_InitialDatabaseCreation")]
    partial class InitialDatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Blah", b =>
                {
                    b.Property<int>("BlahId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlahValue")
                        .HasMaxLength(50);

                    b.HasKey("BlahId");

                    b.ToTable("Blahs");
                });

            modelBuilder.Entity("Domain.FooBar", b =>
                {
                    b.Property<int>("FooBarId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FooBarValue")
                        .HasMaxLength(50);

                    b.HasKey("FooBarId");

                    b.ToTable("FooBars");
                });
#pragma warning restore 612, 618
        }
    }
}
